[package]
name = "formi"
version = "0.1.0"
edition = "2024"

[dependencies]
phf = { version = "0.13.1", features = ["macros"] }
thiserror = "2.0.17"

[features]
default = ["repl"]
std = []
repl = ["std"]
